id: P006961
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4782
  title: བློ་གསར་རིགས་ལམ་མིག་འབྱེད
  author: ''
  volumes:
    9923572ec97441368aaad855b4118172:
      image_group_id: I1KG4843
      title: ''
      volume_number: 1
      total_pages: 140
ebook_metadata:
  title: བློ་གསར་རིགས་ལམ་མིག་འབྱེད
  author: ''
  sku: P006961
  cover: cover.jpg
  layers:
  - pagination
